name: learniverse_client
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.2
  filesystem_picker: ^3.1.0
  file_picker: ^5.2.2
  path_provider: ^2.0.13
  provider: ^6.0.5
  firebase_core: ^2.19.0
  fluttertoast: ^8.2.2
  go_router: ^12.0.0
  firebase_database: ^10.3.1
  flutter_quill: ^8.1.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

